language: rust

rust:
  - stable
  - beta
  - nightly

before_script:
  - rustup component add rustfmt

script:
  - cargo fmt -- --check
  - cargo build --verbose
  - cargo test --verbose

jobs:
  fast_finish: true
  allow_failures:
    - rust: nightly
