name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always


jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          cargo fmt -- --check
          cargo test --verbose

      - name: Build
        run: cargo build --verbose

      - uses: actions/upload-artifact@v2
        with:
          name: release
          path: ./target/release/cleanup*
