name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always


jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            exe: cleanup
          - os: windows-latest
            exe: cleanup.exe

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run tests
        run: |
          cargo fmt -- --check
          cargo test --verbose

      - name: Build
        run: |
          cargo build --release --verbose
          sha1sum -b ./target/release/${{ matrix.exe }} >> ./target/release/${{ matrix.exe }}.txt
          sha256sum -b ./target/release/${{ matrix.exe }} >> ./target/release/${{ matrix.exe }}.txt
          sha512sum -b ./target/release/${{ matrix.exe }} >> ./target/release/${{ matrix.exe }}.txt
          md5sum -b ./target/release/${{ matrix.exe }} >> ./target/release/${{ matrix.exe }}.txt

      - uses: actions/upload-artifact@v2
        with:
          name: release
          path: |
            ./target/release/${{ matrix.exe }}
            ./target/release/${{ matrix.exe }}.txt
